ALTER TABLE public.qr_menus
ADD COLUMN IF NOT EXISTS title_tr TEXT,
ADD COLUMN IF NOT EXISTS subtitle_tr TEXT,
ADD COLUMN IF NOT EXISTS active_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS cover_url TEXT,
ADD COLUMN IF NOT EXISTS theme_id TEXT DEFAULT 'theme1';
