ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS preparation_time INTEGER,
ADD COLUMN IF NOT EXISTS allergens TEXT,
ADD COLUMN IF NOT EXISTS tags TEXT[],
ADD COLUMN IF NOT EXISTS calories INTEGER,
ADD COLUMN IF NOT EXISTS kitchen_start_time TIME,
ADD COLUMN IF NOT EXISTS kitchen_end_time TIME;
